include:
  - project: 'antwerpen/across/across-development'
    file:
      - '/gitlab-ci/docker.gitlab-ci.yml'
      - '/gitlab-ci/common.gitlab-ci.yml'
      - '/gitlab-ci/unit-tests.gitlab-ci.yml'
      - '/gitlab-ci/unit-tests-docker.gitlab-ci.yml'
      - '/gitlab-ci/integration-tests-docker.gitlab-ci.yml'
      - '/gitlab-ci/deploy.gitlab-ci.yml'

variables:
  NODEJS_DOCKER_IMAGE_VERSION: 12

.frontend:
  stage: test
  # TODO: node:16 does not work for ax-bootstrap-theme, but does for bootstrap-ui-module and entity-module:
  # image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODEJS_DOCKER_IMAGE_VERSION}
  script:
    - cd ${MODULE_NAME}/src/main/frontend
    - yarn install
    - yarn build:prod

frontend:bootstrap-ui-module:
  extends:
    - .frontend
  variables:
    MODULE_NAME: bootstrap-ui-module
  artifacts:
    paths:
      - bootstrap-ui-module/src/main/resources/views/static/BootstrapUiModule/

frontend:entity-module:
  extends:
    - .frontend
  variables:
    MODULE_NAME: entity-module
  artifacts:
    paths:
      - entity-module/src/main/resources/views/static/entity/

frontend:ax-bootstrap-theme:
  extends:
    - .frontend
  variables:
    MODULE_NAME: ax-bootstrap-theme
  artifacts:
    paths:
      - ax-bootstrap-theme/src/main/resources/views/static/adminweb-themes/


build:test-apps:
  stage: test
  needs:
    - frontend:bootstrap-ui-module
    - frontend:entity-module
    # - frontend:ax-bootstrap-theme
  script:
    # - 'mvn $MAVEN_CLI_OPTS dependency:purge-local-repository -DmanualInclude=com.foreach -DreResolve=false'
    - find $CI_PROJECT_DIR/.m2/repository/com/foreach/ -type d -name "*-SNAPSHOT" | xargs rm -rf || echo "No snapshots to delete"
    - 'mvn $MAVEN_CLI_OPTS package -DskipTests'
  artifacts:
    when: always
    paths:
      - '*/target/*-exec.jar'


.end2end:
  stage: test
  needs:
    - build:test-apps
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}-dind
      alias: docker
      command: [ "--tls=false" ]
  before_script:
    - docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
  script:
    - cd $MODULE_NAME
    - echo "DOCKER_REPOSITORY=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}" > .env
    - cat .env
    - docker-compose --ansi=never up e2e
  after_script:
    - docker-compose down
  artifacts:
    when: always
    reports:
      junit:
        - $MODULE_NAME/src/test/e2e/tests/cypress/out/*.xml
    paths:
      - $MODULE_NAME/src/test/e2e/tests/cypress/out/videos/

end2end:bootstrap-ui-module:
  extends:
    - .end2end
  variables:
    MODULE_NAME: bootstrap-ui-module-test

end2end:entity-module:
  extends:
    - .end2end
  variables:
    MODULE_NAME: entity-module-test-application
